### ISSUE TITLE
Unidepth issue

### ISSUE THREAD

**Issue by ShreyaIAB** [jagennath-hari/RGBD-3DGS-SLAM#2]
Hi, 
Thanks for your work. It is really interesting.  I am also interested in something similar and would like to try out with your rep. My idea is to test it out and then test out with many other depth estimation models with MonoGS.

However i am facing issue with pip install unidepth. 
![Screenshotmonogsharij](https://github.com/user-attachments/assets/d03b83f1-b00c-472d-898e-ed77ca61f9e9)
I think if i can fix this, then i should be able to test out your rep.

I am using  - 
1. WSL 22.04
2.  CUDA Version: 12.4 

Thanks!

**Comment by jagennath-hari** [comment]
Hi, 

You might using a CUDA version which is too new, but I'm not sure as PyTorch for CUDA 12.4 is available. Can you go to the official UniDepth repository try to install, and then show me which dependencies aren't being met/installed.

**Comment by ShreyaIAB** [comment]
I am struggling to get UniDepth working due to some environmental issues. But i got Anydepthv2 working in a similar env as MonoGS

**Comment by jagennath-hari** [comment]
Glad you could get something working, just make sure to refactor the dataset.py in MonoGS to accommodate other networks. Very curious to see the results it will produce. Feel free ask for any help if you have issues with the dataloaders.

**Comment by ShreyaIAB** [comment]
Sure, the idea is since I am struggling with UniDepth (i got it working in a different system with CUDA 12.1, but the same steps fails in mine, i tried a lot of things but didnt succeed), i would be replacing unidepth wirh anydepthv2 and will try to get ur rep working. I have not looked at the code, i will contact you if help is needed. We have connected on Linkedin :) Also Padma connected with you few days back on Linkedin as well, we are collegues working towards similar projects.

**Comment by LoganCome** [comment]
@ShreyaIAB 
Dear shreyal, I met the same error when I run this project. Could you tell me some specific steps to solve this issue?

**Comment by ShreyaIAB** [comment]
@LoganCome Hi, I am sorry, i had not fixed this issue

**Comment by ShreyaIAB** [comment]
@LoganCome hey, just curious, how did u solve this issue? :)

**Comment by LoganCome** [comment]
@ShreyaIAB , in another issue, the author provide some ways to address this. https://github.com/jagennath-hari/RGBD-3DGS-SLAM/issues/6#issuecomment-2316440788
