### ISSUE TITLE
Pip subprocess error:

### ISSUE THREAD

**Issue by LoganCome** [jagennath-hari/RGBD-3DGS-SLAM#4]
Dear Author,

When i install with "conda env create -f environment.yml", I met the following error:

Pip subprocess error:
ERROR: Ignored the following yanked versions: 2.0.0
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement torchaudio==2.2.0+cu121 (from versions: 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torchaudio==2.2.0+cu121

failed

CondaEnvException: Pip failed

**Comment by jagennath-hari** [comment]
Hi,

Can you try to change the torchaudio==2.2.0+cu121 in the environment.yml file to just  torchaudio==2.2.0. 

Let me know how it goes.

**Comment by LoganCome** [comment]
@jagennath-hari 
Thanks for your reply! I have followed you advice to revise "torchaudio==2.2.0+cu121" to "torchaudio==2.2.0", there is no error output about torchaudio. But there still errors about unidepth:

```
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement unidepth==0.1 (from versions: none)
ERROR: No matching distribution found for unidepth==0.1

failed

CondaEnvException: Pip failed
```

**Comment by LoganCome** [comment]
@jagennath-hari 

Dear author, I have addressed this issue with directly pip install in the source code folder. Thanks a lot!
