### ISSUE TITLE
Error loading UniDepthV2 model: Parameter size mismatch

### ISSUE THREAD

**Issue by LoganCome** [jagennath-hari/RGBD-3DGS-SLAM#6]
Dear author,

I'm encountering an error when trying to load the UniDepthV2 model from the pretrained weights. The error suggests a mismatch between the expected parameter sizes and the actual sizes in the current model. As the following figure:

![image](https://github.com/user-attachments/assets/a8183d55-4f4e-4f71-b334-a53cdadc4669)

Errors output:

```
RuntimeError:
Error(s) in loading state_dict for UniDepthV2:
        size mismatch for pixel_decoder.depth_layer.ups.0.up.1.weight: copying a param with shape torch.Size([128, 1, 7, 7]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
        size mismatch for pixel_decoder.depth_layer.ups.0.up.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for pixel_decoder.depth_layer.ups.1.up.1.weight: copying a param with shape torch.Size([64, 1, 7, 7]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
        size mismatch for pixel_decoder.depth_layer.ups.1.up.1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for pixel_decoder.depth_layer.ups.2.up.1.weight: copying a param with shape torch.Size([32, 1, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 32, 3, 3]).
        size mismatch for pixel_decoder.depth_layer.ups.2.up.1.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
```

Thank you for your time and assistance.

**Comment by jagennath-hari** [comment]
Hi,

Can you try other variants of the Unidepth V2 models like ViT-S or maybe try V1's ViT-L or ConvNext-L as a start. The Unidepth depth networks comes from the author of their paper and codebase. If the issue still persists let me pull the recent variant shortly and test the V2's ViT-L. 

Maybe you could try using torch hub too, example given below.

version = "v2"
backbone = "vitl14"

self.depth_model = torch.hub.load("lpiccinelli-eth/UniDepth", "UniDepth", version=version, backbone=backbone, pretrained=True, trust_repo=True, force_reload=True)
